services:
  gimbal-agent:
    build: .
    container_name: cv_agent_container
    volumes:
      - .:/app
    # Ẩn 2 dòng dưới đây để Docker không đòi Webcam vật lý nữa
    # devices:
    #   - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=$DISPLAY
    network_mode: "host"